---
#
#    Debian 7 (wheezy) PHP Stack (docker-compose.override.sample.yml)
#    Copyright (C) 2016-2017 Stafli
#    Luís Pedro Algarvio
#    This file is part of the Stafli Application Stack.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# For Docker Compose v2+ only
version: '2'

#
# Services
#
services:

  stack_php56_cache_memcached14_debian7:
    build:
      args:
        app_memcached_loglevel: "verbose"
        app_memcached_listen_port: "11211"
        app_memcached_limit_backlog: "256"
        app_memcached_limit_concurent: "256"
        app_memcached_limit_memory: "128"
    ports:
      - "11211"

  stack_php56_cache_redis32_debian7:
    build:
      args:
        app_redis_loglevel: "verbose"
        app_redis_listen_port: "6379"
        app_redis_listen_timeout: "5"
        app_redis_limit_backlog: "256"
        app_redis_limit_concurent: "256"
        app_redis_limit_memory: "134217728"
    ports:
      - "6379"

  stack_php56_rdbms_mariadb10_debian7:
    build:
      args:
        app_mariadb_global_loglevel: "verbose"
        app_mariadb_global_listen_port: "3306"
        app_mariadb_global_default_storage_engine: "InnoDB"
        app_mariadb_global_default_character_set: "utf8"
        app_mariadb_global_default_collation: "utf8_general_ci"
        app_mariadb_tuning_max_connections: "100"
        app_mariadb_tuning_connect_timeout: "5"
        app_mariadb_tuning_wait_timeout: "600"
        app_mariadb_tuning_max_allowed_packet: "128M"
        app_mariadb_tuning_thread_cache_size: "128"
        app_mariadb_tuning_sort_buffer_size: "4M"
        app_mariadb_tuning_bulk_insert_buffer_size: "16M"
        app_mariadb_tuning_tmp_table_size: "32M"
        app_mariadb_tuning_max_heap_table_size: "32M"
        app_mariadb_query_cache_limit: "128K"
        app_mariadb_query_cache_size: "64M"
        app_mariadb_query_cache_type: "DEMAND"
        app_mariadb_myisam_key_buffer_size: "128M"
        app_mariadb_myisam_myisam_sort_buffer_size: "512M"
        app_mariadb_myisam_read_buffer_size: "2M"
        app_mariadb_myisam_read_rnd_buffer_size: "1M"
        app_mariadb_innodb_log_file_size: "50M"
        app_mariadb_innodb_buffer_pool_size: "256M"
        app_mariadb_innodb_log_buffer_size: "8M"
    ports:
      - "3306"

  stack_php56_language_php56_debian7:
    build:
      args:
        app_php_global_limit_timeout: "120"
        app_php_global_limit_memory: "134217728"
        app_fpm_global_limit_processes: "128"
        app_fpm_pool_listen_port: "9000"
        app_fpm_pool_limit_backlog: "65536"
        app_fpm_pool_pm_method: "dynamic"
        app_fpm_pool_pm_max_children: "100"
        app_fpm_pool_pm_start_servers: "20"
        app_fpm_pool_pm_min_spare_servers: "10"
        app_fpm_pool_pm_max_spare_servers: "30"
        app_fpm_pool_pm_process_idle_timeout: "10s"
        app_fpm_pool_pm_max_requests: "5000"
    ports:
      - "9000"

  stack_php56_web_httpd22_debian7:
    build:
      args:
        app_httpd_global_listen_port_http: "8080"
        app_httpd_global_listen_port_https: "8443"
        app_httpd_global_listen_timeout: "140"
        app_httpd_global_listen_keepalive_status: "On"
        app_httpd_global_listen_keepalive_requests: "100"
        app_httpd_global_listen_keepalive_timeout: "5"
        app_httpd_vhost_listen_port_http: "8080"
        app_httpd_vhost_listen_port_https: "8443"
        app_httpd_vhost_fpm_port: "9000"
    ports:
      - "8080"
      - "8443"

  stack_php56_proxy_httpd22_debian7:
    build:
      args:
        app_httpd_global_listen_port_http: "8080"
        app_httpd_global_listen_port_https: "8443"
        app_httpd_global_listen_timeout: "145"
        app_httpd_global_listen_keepalive_status: "On"
        app_httpd_global_listen_keepalive_requests: "100"
        app_httpd_global_listen_keepalive_timeout: "5"
        app_httpd_vhost_listen_port_http: "8080"
        app_httpd_vhost_listen_port_https: "8443"
    ports:
      - "8080"
      - "8443"

