---
#
#    CentOS 7 (centos7) docker-compose.yml
#    Copyright (C) 2016 SOL-ICT
#    This file is part of the Docker High Performance PHP Stack.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# For Docker Compose v2+ only
version: '2'

#
# Services/profiles
#
services:

  memcached14:
    labels:
      - "org.label-schema.schema-version=1.0"
      - "org.label-schema.name=$PROJECT_NAME - Memcached 1.4.x service"
      - "org.label-schema.description=Based on $PROJECT_FROM - Standard service"
      - "org.label-schema.vendor=$PROJECT_VENDOR"
      - "org.label-schema.url=$PROJECT_URL"
      - "license=$PROJECT_LICENSE"
      - "org.label-schema.vcs-ref=$VCS_REF"
      - "org.label-schema.vcs-url=$VCS_URL"
      - "os-id=$OS_ID"
      - "os-version-id=$OS_VERSION_ID"
      - "architecture=$BUILD_ARCH"
      - "org.label-schema.version=$BUILD_VERSION"
      - "org.label-schema.build-date=$BUILD_DATE"
    image: "solict/high-performance-php-stack:centos7_memcached14"
    build:
      context: "./dockerfiles"
      dockerfile: "memcached14.dockerfile"
      args:
        app_memcached_user: "memcached"
        app_memcached_group: "memcached"
        app_memcached_home: "/run/memcached"
        app_memcached_loglevel: "notice"
        app_memcached_auth_sasl: "no"
        app_memcached_listen_proto: "auto"
        app_memcached_listen_addr: "0.0.0.0"
        app_memcached_listen_port: "11211"
        app_memcached_limit_backlog: "256"
        app_memcached_limit_concurent: "256"
        app_memcached_limit_memory: "128"
    logging:
      driver: "json-file"
    networks:
      - backend
    ports:
      - "22"
      - "11211"
    working_dir: "/tmp"
    command: "/usr/bin/supervisord -c /etc/supervisord.conf --nodaemon"

  redis30:
    labels:
      - "org.label-schema.schema-version=1.0"
      - "org.label-schema.name=$PROJECT_NAME - Redis 3.0.x service"
      - "org.label-schema.description=Based on $PROJECT_FROM - Standard service"
      - "org.label-schema.vendor=$PROJECT_VENDOR"
      - "org.label-schema.url=$PROJECT_URL"
      - "license=$PROJECT_LICENSE"
      - "org.label-schema.vcs-ref=$VCS_REF"
      - "org.label-schema.vcs-url=$VCS_URL"
      - "os-id=$OS_ID"
      - "os-version-id=$OS_VERSION_ID"
      - "architecture=$BUILD_ARCH"
      - "org.label-schema.version=$BUILD_VERSION"
      - "org.label-schema.build-date=$BUILD_DATE"
    image: "solict/high-performance-php-stack:centos7_redis30"
    build:
      context: "./dockerfiles"
      dockerfile: "redis30.dockerfile"
      args:
        app_redis_user: "redis"
        app_redis_group: "redis"
        app_redis_home: "/var/lib/redis"
        app_redis_loglevel: "notice"
        app_redis_listen_addr: "0.0.0.0"
        app_redis_listen_port: "6379"
        app_redis_listen_timeout: "5"
        app_redis_listen_keepalive: "60"
        app_redis_limit_backlog: "256"
        app_redis_limit_concurent: "256"
        app_redis_limit_memory: "134217728"
    logging:
      driver: "json-file"
    networks:
      - backend
    ports:
      - "22"
      - "6379"
    working_dir: "/tmp"
    command: "/usr/bin/supervisord -c /etc/supervisord.conf --nodaemon"

  mysql55:
    labels:
      - "org.label-schema.schema-version=1.0"
      - "org.label-schema.name=$PROJECT_NAME - MySQL 5.5.x service"
      - "org.label-schema.description=Based on $PROJECT_FROM - Standard service"
      - "org.label-schema.vendor=$PROJECT_VENDOR"
      - "org.label-schema.url=$PROJECT_URL"
      - "license=$PROJECT_LICENSE"
      - "org.label-schema.vcs-ref=$VCS_REF"
      - "org.label-schema.vcs-url=$VCS_URL"
      - "os-id=$OS_ID"
      - "os-version-id=$OS_VERSION_ID"
      - "architecture=$BUILD_ARCH"
      - "org.label-schema.version=$BUILD_VERSION"
      - "org.label-schema.build-date=$BUILD_DATE"
    image: "solict/high-performance-php-stack:centos7_mysql55"
    build:
      context: "./dockerfiles"
      dockerfile: "mysql55.dockerfile"
      args:
        app_mysql_user: "mysql"
        app_mysql_group: "mysql"
        app_mysql_home: "/var/lib/mysql"
        app_mysql_listen_addr: "0.0.0.0"
        app_mysql_listen_port: "3306"
    logging:
      driver: "json-file"
    networks:
      - backend
    ports:
      - "22"
      - "3306"
    working_dir: "/tmp"
    command: "/usr/bin/supervisord -c /etc/supervisord.conf --nodaemon"

  php56:
    labels:
      - "org.label-schema.schema-version=1.0"
      - "org.label-schema.name=$PROJECT_NAME - PHP 5.6.x service"
      - "org.label-schema.description=Based on $PROJECT_FROM - Devel service"
      - "org.label-schema.vendor=$PROJECT_VENDOR"
      - "org.label-schema.url=$PROJECT_URL"
      - "license=$PROJECT_LICENSE"
      - "org.label-schema.vcs-ref=$VCS_REF"
      - "org.label-schema.vcs-url=$VCS_URL"
      - "os-id=$OS_ID"
      - "os-version-id=$OS_VERSION_ID"
      - "architecture=$BUILD_ARCH"
      - "org.label-schema.version=$BUILD_VERSION"
      - "org.label-schema.build-date=$BUILD_DATE"
    image: "solict/high-performance-php-stack:centos7_php56"
    build:
      context: "./dockerfiles"
      dockerfile: "php56.dockerfile"
      args:
        app_php_exts_core_dis: "mysql"
        app_php_exts_core_en: "mcrypt curl gd imap ldap mysqli mysqlnd odbc pdo pdo_mysql pdo_odbc opcache"
        app_php_exts_extra_dis: "xdebug xhprof"
        app_php_exts_extra_en: "igbinary msgpack yaml solr mongodb memcache memcached redis"
        app_php_global_log_level: "E_ALL"
        app_php_global_log_display: "On"
        app_php_global_log_file: "On"
        app_php_global_limit_timeout: "120"
        app_php_global_limit_memory: "134217728"
        app_fpm_global_user: "apache"
        app_fpm_global_group: "apache"
        app_fpm_global_home: "/var/www"
        app_fpm_global_log_level: "notice"
        app_fpm_global_limit_descriptors: "1024"
        app_fpm_global_limit_processes: "128"
        app_fpm_pool_id: "default"
        app_fpm_pool_user: "apache"
        app_fpm_pool_group: "apache"
        app_fpm_pool_listen_wlist: "0.0.0.0"
        app_fpm_pool_listen_addr: "0.0.0.0"
        app_fpm_pool_listen_port: "9000"
        app_fpm_pool_limit_descriptors: "1024"
        app_fpm_pool_limit_backlog: "256"
        app_fpm_pool_pm_method: "dynamic"
        app_fpm_pool_pm_max_children: "100"
        app_fpm_pool_pm_start_servers: "20"
        app_fpm_pool_pm_min_spare_servers: "10"
        app_fpm_pool_pm_max_spare_servers: "30"
        app_fpm_pool_pm_process_idle_timeout: "10s"
        app_fpm_pool_pm_max_requests: "5000"
    depends_on:
      - memcached14
      - redis30
      - mysql55
    links:
      - memcached14
      - redis30
      - mysql55
    logging:
      driver: "json-file"
    networks:
      - application
      - backend
    ports:
      - "22"
      - "9000"
    working_dir: "/tmp"
    command: "/usr/bin/supervisord -c /etc/supervisord.conf --nodaemon"

  httpd24_web:
    labels:
      - "org.label-schema.schema-version=1.0"
      - "org.label-schema.name=$PROJECT_NAME - HTTPd 2.4.x Web service"
      - "org.label-schema.description=Based on $PROJECT_FROM - Standard service"
      - "org.label-schema.vendor=$PROJECT_VENDOR"
      - "org.label-schema.url=$PROJECT_URL"
      - "license=$PROJECT_LICENSE"
      - "org.label-schema.vcs-ref=$VCS_REF"
      - "org.label-schema.vcs-url=$VCS_URL"
      - "os-id=$OS_ID"
      - "os-version-id=$OS_VERSION_ID"
      - "architecture=$BUILD_ARCH"
      - "org.label-schema.version=$BUILD_VERSION"
      - "org.label-schema.build-date=$BUILD_DATE"
    image: "solict/high-performance-php-stack:centos7_httpd24_web"
    build:
      context: "./dockerfiles"
      dockerfile: "httpd24-web.dockerfile"
      args:
        app_httpd_global_mods_core_dis: "allowmethods asis auth_digest auth_form authn_anon authn_dbd authn_dbm authn_socache authnz_fcgi authnz_ldap authz_dbd authz_dbm authz_owner buffer cache cache_disk cache_socache cgi cgid charset_lite dav_fs dav dav_lock data dbd dialup dump_io echo ext_filter file_cache heartbeat heartmonitor ident include lbmethod_bybusyness lbmethod_byrequests lbmethod_bytraffic lbmethod_heartbeat ldap log_debug log_forensic lua mime_magic negotiation proxy_balancer proxy_connect proxy_express proxy_fdpass proxy_ftp proxy_html proxy_scgi proxy_wstunnel ratelimit reflector remoteip reqtimeout request sed session_crypto session_dbd slotmem_plain slotmem_shm socache_dbm socache_memcache speling substitute suexec unique_id userdir usertrack vhost_alias xml2enc"
        app_httpd_global_mods_core_en: "mpm_event macro alias dir autoindex mime setenvif env expires headers filter deflate rewrite actions authn_core authn_file authz_core authz_groupfile authz_host authz_user auth_basic access_compat session session_cookie socache_shmcb ssl proxy proxy_ajp proxy_fcgi proxy_http info status"
        app_httpd_global_mods_extra_dis: "authnz_external"
        app_httpd_global_mods_extra_en: "upload_progress xsendfile"
        app_httpd_global_user: "apache"
        app_httpd_global_group: "apache"
        app_httpd_global_home: "/var/www"
        app_httpd_global_loglevel: "warn"
        app_httpd_global_listen_addr: "0.0.0.0"
        app_httpd_global_listen_port_http: "80"
        app_httpd_global_listen_port_https: "443"
        app_httpd_global_listen_timeout: "140"
        app_httpd_global_listen_keepalive_status: "On"
        app_httpd_global_listen_keepalive_requests: "100"
        app_httpd_global_listen_keepalive_timeout: "5"
        app_httpd_vhost_id: "default"
        app_httpd_vhost_user: "apache"
        app_httpd_vhost_group: "apache"
        app_httpd_vhost_listen_addr: "0.0.0.0"
        app_httpd_vhost_listen_port_http: "80"
        app_httpd_vhost_listen_port_https: "443"
        app_httpd_vhost_httpd_wlist: "ip 127.0.0.1 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
        app_httpd_vhost_fpm_wlist: "ip 127.0.0.1 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
        app_httpd_vhost_fpm_addr: "centos7_php56_1"
        app_httpd_vhost_fpm_port: "9000"
    depends_on:
      - php56
    links:
      - php56
    logging:
      driver: "json-file"
    networks:
      - frontend
      - application
    ports:
      - "22"
      - "80"
      - "443"
    working_dir: "/tmp"
    command: "/usr/bin/supervisord -c /etc/supervisord.conf --nodaemon"

  httpd24_proxy:
    labels:
      - "org.label-schema.schema-version=1.0"
      - "org.label-schema.name=$PROJECT_NAME - HTTPd 2.4.x Proxy service"
      - "org.label-schema.description=Based on $PROJECT_FROM - Standard service"
      - "org.label-schema.vendor=$PROJECT_VENDOR"
      - "org.label-schema.url=$PROJECT_URL"
      - "license=$PROJECT_LICENSE"
      - "org.label-schema.vcs-ref=$VCS_REF"
      - "org.label-schema.vcs-url=$VCS_URL"
      - "os-id=$OS_ID"
      - "os-version-id=$OS_VERSION_ID"
      - "architecture=$BUILD_ARCH"
      - "org.label-schema.version=$BUILD_VERSION"
      - "org.label-schema.build-date=$BUILD_DATE"
    image: "solict/high-performance-php-stack:centos7_httpd24_proxy"
    build:
      context: "./dockerfiles"
      dockerfile: "httpd24-proxy.dockerfile"
      args:
        app_httpd_global_mods_core_dis: "allowmethods asis auth_digest auth_form authn_anon authn_dbd authn_dbm authn_socache authnz_fcgi authnz_ldap authz_dbd authz_dbm authz_owner buffer cache cache_disk cache_socache cgi cgid charset_lite dav_fs dav dav_lock data dbd dialup dump_io echo ext_filter file_cache heartbeat heartmonitor ident include lbmethod_bybusyness lbmethod_byrequests lbmethod_bytraffic lbmethod_heartbeat ldap log_debug log_forensic lua mime_magic negotiation proxy_ajp proxy_balancer proxy_connect proxy_express proxy_fcgi proxy_fdpass proxy_ftp proxy_html proxy_scgi proxy_wstunnel ratelimit reflector remoteip reqtimeout request sed session_crypto session_dbd slotmem_plain slotmem_shm socache_dbm socache_memcache speling substitute suexec unique_id userdir usertrack vhost_alias xml2enc"
        app_httpd_global_mods_core_en: "mpm_event macro alias dir autoindex mime setenvif env expires headers filter deflate rewrite actions authn_core authn_file authz_core authz_groupfile authz_host authz_user auth_basic access_compat session session_cookie socache_shmcb ssl proxy proxy_http info status"
        app_httpd_global_mods_extra_dis: "authnz_external"
        app_httpd_global_mods_extra_en: "upload_progress xsendfile"
        app_httpd_global_user: "apache"
        app_httpd_global_group: "apache"
        app_httpd_global_home: "/var/www"
        app_httpd_global_loglevel: "warn"
        app_httpd_global_listen_addr: "0.0.0.0"
        app_httpd_global_listen_port_http: "80"
        app_httpd_global_listen_port_https: "443"
        app_httpd_global_listen_timeout: "145"
        app_httpd_global_listen_keepalive_status: "On"
        app_httpd_global_listen_keepalive_requests: "100"
        app_httpd_global_listen_keepalive_timeout: "5"
        app_httpd_vhost_id: "default"
        app_httpd_vhost_user: "apache"
        app_httpd_vhost_group: "apache"
        app_httpd_vhost_listen_addr: "0.0.0.0"
        app_httpd_vhost_listen_port_http: "80"
        app_httpd_vhost_listen_port_https: "443"
        app_httpd_vhost_httpd_wlist: "ip 127.0.0.1 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
    depends_on:
      - httpd24_web
    links:
      - httpd24_web
    logging:
      driver: "json-file"
    networks:
      - proxy
      - frontend
    ports:
      - "22"
      - "80"
      - "443"
    working_dir: "/tmp"
    command: "/usr/bin/supervisord -c /etc/supervisord.conf --nodaemon"

#
# Networks
#
networks:
  default:
    driver: "bridge"
  proxy:
    driver: "bridge"
  frontend:
    driver: "bridge"
  application:
    driver: "bridge"
  backend:
    driver: "bridge"

